#!/sbin/busybox sh

#originally By Andrei

export PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin

exec 1<&-
exec 2<&-
exec 1<>/init_log_secondary
exec 2>&1

TAG="[Init2] :"

echo "Secondary init redirected" > /init_redir
echo $TAG "redirect done"

echo $TAG "busybox done"


loadSynapse () {
	echo $TAG "synapse start"

	chmod -R 775 /res/synapse/*
	
	echo $TAG "UCI init"
	uci
	
	echo $TAG "synapse done"
}



echo $TAG "mounting.."

mount -o rw,remount system /system

loadSynapse

echo $TAG "mounting system r/o"
mount -o ro,remount system /system

chmod 0755 /proc/last_kmsg
chmod 0755 /init_log_primary
chmod 0755 /init_log_secondary

echo $TAG "mounting rootfs r/o"
cd /
mount -t rootfs -o remount,ro rootfs

. /res/gundal.sh
