#!/sbin/busybox sh

cd /sbin

for i in $(./busybox --list)
do
	./busybox ln -s busybox $i
done

cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

exec 1<&-
exec 2<&-
exec 1<>/init_log_primary
exec 2>&1

echo "Primary init redirected" > /init_redir
echo "Init redirected"

cat /proc/partitions

rm /init
mv /init2 /init

mkdir GuNDaL

exec /init
exit
